### ISSUE TITLE
Migrate data from Static12 to Titan

### ISSUE THREAD

**Issue by ELD** [unkso/titan-app#54]
## Description

We should be able to migrate users and user files from static12 to Titan transparently. This would seed data on day one and make the transition that much smoother as member history would come over without a hitch.

## Requirements/Expected Behavior

Despite us only having to do this once, this should be in the form of a script or binary that we can run and it just works (or SQL query, if that's easier) and have some rudimentary error handling (see requirements below).

It should:

- Export data from static12 (fetch, export, etc)
- Massage it into the form that Titan is expecting
- Insert that data into Titan's database tables
  - Insert data in such a way that individual record failures can be reported (i.e. row-by-row)
- Report any failures so they can be addressed by hand
- Add ACL entries for all those NCO and above so they can add user files

**Comment by MichaelJamesParsons** [comment]
We can retrieve data from static12 and structure it to conform to titan's schema with SQL. Then consolidate the results into a single SQL file as `insert` statements. The inserts can be tested on a fresh local copy of titan. Any errors will be clearly written out in the terminal so we can debug and resolve any issues that come up. Then we can run that file on production once with confidence that it will succeed.

The SQL statements for exporting each entity into titan's schema are already written, so our effort will be reduced to consolidating the insert statements and debugging edge cases that arise. While running these SQL queries earlier, only one error occurred due to a unique constraint violation. The record that caused the error was old. I don't foresee significant complications with the most recent clone of static12, since it's only a couple months older than the last copy I tested.

Writing a dedicated script introduces it's own level of complexity:
- juggle multiple import files (CSV?) or connect to both static12 and titan and configure the schema for both.
- boilerplate data structures to map to the old DB tables.
- convert old schema to new (can be easily achieved with sql instead).
- logging errors will give us the same information as if we used SQL.

Considering this is a one-off migration, I believe the amount of additional work to write a migration script outweighs the effort required to use a SQL solution.

**Comment by ELD** [comment]
@MichaelJamesParsons The preceding snippet migrates data from static12 to Titan while resetting IDs on users. It transfers over all the valid users and files. It also updates the player record in static12 that causes a duplicate key integrity violation. I used this to import the data into Titan in its current form. Profiles appear to be correct now.

**Comment by ELD** [comment]
I'm going to call this one done and close the issue.
